lightly-ai/lightly-train

examples/notebooks/rfdetr.ipynb
=> Remove API Key

.github/pull_request_template.md
- small update to PR template to make sure we don't forget to also update the docs
=> update PR templated

src/lightly_train/_methods/distillation/distillation.py, src/lightly_train/_methods/distillationv2/distillationv2.py, src/lightly_train/_modules/teachers/dinov2/build_teacher.py
Ensures that only the rank 0 from each node downloads the checkpoint.
No additional tests are implemented.
=> Handle concurrent downloads

tests/_commands/test_export.py, tests/_commands/test_train.py
* Add test that checkpoints are loaded correctly
* Updated unit tests
* Made test fail by introducing wrong checkpoint loading that was fixed in a previous PR
=> Test checkpoint loading

CHANGELOG.md, docs/source/methods/distillation.md, src/lightly_train/_methods/method_helpers.py, tests/_methods/test_method_helpers.py
Made DistillationV2 visible.
Updated existing test to check the list of method and the mapping from method names to method classes.
=> Distillationv2 interface

src/lightly_train/_callbacks/export.py
Ensures the model is only exported and removed from rank 0.
Successfully runs for 100 epochs on 4 GPUs without crashing.
=> Export and remove models from rank 0 only

src/lightly_train/_methods/distillationv2/distillationv2.py
Changed the projection head that maps student features to the teacher embedding space from a linear layer to a small MLP.
Dummy train run.
=> DistillationV2 projection head is a MLP

README.md
Update the readme to state that we offer free licenses for academic usage or small startups.
N/A
=> Add free community license

docs/source/_templates/sidebar/version.html
Fix the version links in the docs to ensure it is working in the official version. Locally, this would not work anymore.
=> Fix the version link

src/lightly_train/_cli.py, src/lightly_train/_commands/common_helpers.py, src/lightly_train/_env.py, src/lightly_train/_logging.py, tests/test__logging.py
* Cleanup SLURM_JOB_ID env var handling
* Cleanup LIGHTLY_TRAIN_LOG_LEVEL env var handling
* Unit tests
=> Cleanup last env vars

CHANGELOG.md, docs/source/models/custom_models.md, docs/source/models/rtdetr.md, src/lightly_train/_models/model_wrapper.py, src/lightly_train/_models/package_helpers.py, tests/_models/test_model_wrapper.py, tests/_models/test_package_helpers.py
* Update custom model docs to include `get_model` info
* Update error message when a custom model is missing some methods
* Added unit test
* Tested manually
=> Update custom model docs

src/lightly_train/_loggers/mlflow.py
Somehow one of the files was not correctly formatted.
=> Format code

src/lightly_train/_methods/dinov2/dinov2.py, src/lightly_train/_methods/method.py, tests/_methods/dinov2/test_dinov2.py
* Use EmbeddingModel as attribute
* Add DINOv2Head
The changes give us more leeway to refactor the dinov2 code without introducing breaking changes to the overall DINOv2 `state_dict` structure.
* Unit tests
=> Refactor dinov2 module structure

docs/source/models/rtdetr.md
The RT-DETR example was updated to match the expected behavior of our benchmarks.
Ran for a few epochs and compared the loss to the prototype implementation.
=> Update RT-DETR example

Makefile, src/lightly_train/_methods/dinov2/dinov2.py, src/lightly_train/_methods/dinov2/dinov2_head.py
- Koleo loss takes as input [CLS] tokens before the head
- Teacher temperature follows a cosine schedule
- Update the projection head
- Replace gradient cancelling with zeroing of the learning rate for the last layer of the projection head.
Tested by training on IN1K and evaluating with k-NN.
=> DINOv2 bug fixes

.github/copilot-instructions.md
Add instructions for GitHub Copilot
See prompts and responses at
[Copilot Instructions 1d89d9afeeaa800eb7acfc38333741ac.md](https://github.com/user-attachments/files/20694564/Copilot.Instructions.1d89d9afeeaa800eb7acfc38333741ac.md)
=> Add Copilot Instruction

src/lightly_train/_commands/common_helpers.py, src/lightly_train/_commands/train.py, src/lightly_train/_commands/train_helpers.py, src/lightly_train/_commands/train_task.py, src/lightly_train/_commands/train_task_helpers.py, src/lightly_train/_data/infinite_cycle_iterator.py, src/lightly_train/_data/infinite_dataloader_iterator.py, src/lightly_train/_loggers/task_logger_args.py, src/lightly_train/_task_models/dinov2_semantic_segmentation/dinov2_semantic_segmentation.py, src/lightly_train/_task_models/dinov2_semantic_segmentation/dinov2_semantic_segmentation_train.py, src/lightly_train/_task_models/task_train_model.py, tests/_commands/test_common_helpers.py, tests/_commands/test_train_helpers.py, tests/_commands/test_train_task.py
* Init dataloader
* Init model
* Minimal loop
=> Iterate on train loop

src/lightly_train/_task_models/dinov2_semantic_segmentation/dinov2_semantic_segmentation_transforms.py, src/lightly_train/_transforms/semantic_segmentation_transform.py, src/lightly_train/_transforms/transform.py
Implemented transforms for semantic segmentation.
Not tested yet.
=> Thomas trn 645 vfmf s transforms

src/lightly_train/_commands/train_task.py, src/lightly_train/_commands/train_task_helpers.py, src/lightly_train/_task_checkpoint.py, src/lightly_train/_task_models/dinov2_semantic_segmentation/dinov2_semantic_segmentation.py, src/lightly_train/_task_models/dinov2_semantic_segmentation/dinov2_semantic_segmentation_train.py, src/lightly_train/_task_models/task_train_model.py, src/lightly_train/_train_task_state.py
* Save/resume checkpoint
* Handle backbone loading and freezing
* Manually
=> Task checkpoint and backbone handling

CHANGELOG.md, docs/source/methods/dinov2.md, src/lightly_train/_methods/dinov2/dinov2.py, tests/_methods/dinov2/test_dinov2.py
Replacing epoch-based hyperparameters with step-based ones.
Will be tested with a dummy training run.
- [] Not needed (internal change)
- [] Not needed (internal change without effects for user)
=> Thomas trn 637 dinov2 iteration based hp

CHANGELOG.md, README.md, docs/source/index.md, src/lightly_train/__init__.py
release v0.9.0: remove DINOv2 out of beta phase
N/A
=> Release 0.9.0

src/lightly_train/_task_models/dinov2_semantic_segmentation/dinov2_semantic_segmentation.py
* Enable attn mask in seg forward
This increases val metrics in early training stages to match EoMT
=> Enable attn mask in seg forward

README.md
* Fix custom model link
* Followed the link
=> Fix custom models link

src/lightly_train/_commands/train_task.py, src/lightly_train/_task_models/dinov2_semantic_segmentation/dinov2_semantic_segmentation_train.py, src/lightly_train/_task_models/task_train_model.py
* Add gradient clipping
* Unit test
=> Add seg gradient clipping

tests/_commands/test_train_task.py
Skip a test on our runner.
Will be tested by running the tests our CI and verifying that it is skipped.
=> Skip test on our runner.

tests/_commands/test_train_task.py
Changes the condition to skip the test on the self-hosted runner.
Will verify that the test is skipped on the self-hosted runner.
=> Change the test to use "GH_RUNNER_NAME" env var

src/lightly_train/_commands/train_task.py, src/lightly_train/_commands/train_task_helpers.py, src/lightly_train/_data/mask_semantic_segmentation_dataset.py, src/lightly_train/_task_models/dinov2_eomt_semantic_segmentation/task_model.py, src/lightly_train/_task_models/dinov2_eomt_semantic_segmentation/train_model.py, src/lightly_train/_task_models/train_model.py, tests/_commands/test_train_task.py
* Enforce `-eomt` suffix in model name
* Handle default steps and batch size
* Manually
=> Handle EoMT model

src/lightly_train/_task_models/dinov2_eomt_semantic_segmentation/train_model.py
(Delete this: Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.)
=> Fix num joint blocks regex

src/lightly_train/_commands/train_task_helpers.py, src/lightly_train/_data/file_helpers.py, src/lightly_train/_data/image_dataset.py, src/lightly_train/_data/mask_semantic_segmentation_dataset.py, src/lightly_train/_task_models/dinov2_eomt_semantic_segmentation/train_model.py, src/lightly_train/types.py
* Add typing for binary masks
* Make naming more evident
Was confused about our image/masks handling and cleaned it up a bit.
* CI
* Manual test
=> Cleanup binary masks typing

Makefile, dev_tools/dinov3_licenseheader.tmpl, licences/DINOv3_LICENSE.md
- added license and license headers 
- quickly added some files to `src/lightly_train/_models/dinov3_vit`
=> Add DINOv3 license and licenseheaders

src/lightly_train/_callbacks/mlflow_logging.py
Close #256
See issue messages for more details.
Manually .
=> Fix MLflow logging

CHANGELOG.md, src/lightly_train/__init__.py
(Delete this: Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.)
=> Release v0.11.1

Makefile, src/lightly_train/_models/super_gradients/super_gradients_package.py, src/lightly_train/_models/ultralytics/ultralytics.py, src/lightly_train/_models/ultralytics/ultralytics_package.py, tests/_commands/test_export.py
This PR increases the ci/cd dependency cutoff date to 2025/09/07
=> Increase ci depdency cutoff date to 2025-08-07

examples/notebooks/eomt_semantic_segmentation.ipynb, examples/notebooks/semantic_segmentation.ipynb
Colab notebook showing how to use our DINOv3 model weights for inference.
Run it.
=> Add Colab notebook examples for EoMT inference with the model weights

CHANGELOG.md, src/lightly_train/__init__.py
=> Release v0.11.3

NOTICE, README.md
=> Mention license info for DINOv3 weights in README

README.md
(Delete this: Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.)
=> chore: add a link to the social network YouTube

CHANGELOG.md, src/lightly_train/_commands/train.py, src/lightly_train/_commands/train_helpers.py
- overdue
- covered by existing unit-tests
=> Default to bf16-mixed for Pretraining
