CHANGELOG.md
docs/source/installation.md

* Add version compatibility table to docs
I also moved the platform compatibility down and changed it to a table. This way both sections have the same structure. I moved them below the installation instructions as the installation instruction is the most important part and the two tables would take too much space above it.
[Installation - LightlyTrain documentation version table.pdf](https://github.com/user-attachments/files/19796349/Installation.-.LightlyTrain.documentation.version.table.pdf)

Add version compatibility table to docs

---

CHANGELOG.md
src/lightly_train/_models/timm/timm_package.py

Close #29 
See the issue for details.
```python
lightly_train.train(
out="out/vit_dino",
data=data_path,
method="dino",
model="timm/vit_base_patch16_224", # and timm/resnet18
...
)
```

Add `dynamic_img_size=True` to TIMM

---

README.md
docs/source/index.md

* Update logo and benchmark links to make them work from other sites like the [Docs](https://docs.lightly.ai/train/stable/), [PyPI](https://pypi.org/project/lightly-train/), and [DockerHub](https://hub.docker.com/repository/docker/lightly/train/general)
I already updated the DockerHub description. The docs and pypi will be updated with the next release. 
* Tested it on DockerHub

Update logo and benchmark links

---

CHANGELOG.md
docs/source/models/rtdetr.md

The example using RT-DETR is now based on RT-DETRv2 which is backward compatible and has less constraints on packages versions. The example also starts from a randomly initialized backbone.
It has been tested by running the example.

Update RT-DETR to use version 2 and start from random.

---

src/lightly_train/_modules/teachers/dinov2/models/__init__.py

With the changes from #3 , a bug when using pyhton 3.8 was introduced since the carried over code from dinov2 did use removesuffix which is not available in python 3.8. This PR fixes the issue by rewriting the removesuffix to be python 3.8 compatible.

Rewrite removesuffix

---

src/lightly_train/_methods/dinov2/__init__.py
src/lightly_train/_methods/dinov2/dinov2_transform.py
tests/_methods/dinov2/test_dinov2_transform.py

This is the first PR to add dinov2 method to lightly-train. In this PR, the dinov2 transforms are provided. Note: the transforms are basically carried over from dino, only the following params got changed:
```python
class DINOv2RandomResizeArgs(RandomResizeArgs):
min_scale: float = 0.32
class DINOv2LocalViewRandomResizeArgs(RandomResizeArgs):
...
max_scale: float = 0.32
...
class DINOv2LocalViewTransformArgs(PydanticConfig):
num_views: int = 8
...
...
```
unit test to validate the number of views and the shapes are in place.

Trn 366 dinov2 transforms

---

src/lightly_train/_methods/distillationv2/distillationv2_loss.py
tests/_methods/distillationv2/test_distillationv2_loss.py
tests/_methods/distillationv2/test_distillationv2_transforms.py

Add DistillationV2's loss and corresponding tests.
Tests are implemented to check that the loss is a scalar, positive and close to zero when the teacher and student features are identical.

Distillationv2 loss

---

docs/source/index.md
docs/source/methods/dino.md
docs/source/methods/distillation.md
docs/source/methods/index.md
docs/source/methods/simclr.md
docs/source/train/index.md
docs/source/train/method_transform_args.md

* Move augmentation docs under train docs
* This declutters the Method section in the docs. I think it makes sense to put all train related configuration und the train command. 
* Add warning that augmentations should not be changed in most cases
* Makes it a bit clearer that you really shouldn't have to change augmentations.
* Rename augmentations in docs to transforms to be consistent with code
* I found it weird that the docs talk about augmentations but the argument is called `transform_args`. Hope it is a bit clearer now.
* Put default method transforms into dropdown to keep page concise
* I'll do the same when adding the method args. Otherwise the page will be mostly arguments which feels overwhelming.
This PR prepares the docs for adding documentation for the method arguments. …

Move augmentation docs

---

src/lightly_train/_models/timm/timm.py

When loading a timm-wrapped model, it fails if the `global_pool` layer is within `model.head`.
If you now try to use `convnext_base` as a timm model, it now works, while it didn't before.

Fixed bug getting pool layer with timm

---

src/lightly_train/_commands/common_helpers.py
src/lightly_train/_env.py
tests/_commands/test_common_helpers.py

* Allow overwriting the temporary directory used by LightlyTrain
The directory can be overwritten with the `LIGHTLY_TRAIN_TMP_DIR` variable.
Added this as it is also helpful for testing. 
* Unit tests

Add LIGHTLY_TRAIN_TMP_DIR variable

---

CHANGELOG.md
src/lightly_train/_commands/embed.py
src/lightly_train/_commands/export.py
src/lightly_train/_commands/train.py

Make all public function accept only kwargs
[lightly_train - LightlyTrain documentation.pdf](https://github.com/user-attachments/files/20351265/lightly_train.-.LightlyTrain.documentation.pdf)
- [] Yes

Require kwarg for Public Interfaces

---

src/lightly_train/__init__.py

* Disable the albumentations update check
This hides the following warning that pops up if not the latest albumentations version is installed:
```
UserWarning: A new version of Albumentations is available: '2.0.7' (you have '2.0.6'). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
check_for_updates()
```
The check sadly runs at import of albumentations and not when the library is actually used. This is why we have to set the env variable so early.
Tested manually. Didn't write a unit test as it would require manually installed an outdated albumentations version.

Disable albumentations update check

---

tests/_commands/test_train.py

* Use ViT small instead of base for unit tests
Small optimization to speed up unit tests and use less RAM
* CI

Use smaller ViT for unit tests

---

src/lightly_train/_models/dinov2_vit/dinov2_vit_src/models/vision_transformer.py

Since we only so around 10% performance improvement when using xformers, we decide to not bother users by warning about xformers missing.

Only show info when xformers are available

---

docker/Makefile

* Mount variables.mk file when running docker tests
Change was introduced in #75 
Without the fix the tests fail with:
```
make test-from-with-docker -C docker
make: Entering directory '/home/lightly_train/docker'
Makefile:2: variables.mk: No such file or directory
make: Leaving directory '/home/lightly_train/docker'
make: *** No rule to make target 'variables.mk'.  Stop.
make: *** [Makefile:34: test] Error 2
```
* Tested manually

Fix docker test

---

examples/notebooks/rfdetr.ipynb
examples/notebooks/ultralytics_yolo.ipynb

Use distinct datasets for pretraining and fine-tuning in the RFDETR tutorial notebook. 
Make pretraining and fine-tuning into individual sections.
Run on Colab

Update rfdetr notebooks

---

src/lightly_train/_models/dinov2_vit/dinov2_vit_src/configs/train/vitb14.yaml
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/configs/train/vitg14.yaml
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/configs/train/vitl14.yaml
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/configs/train/vits14.yaml

Due to changes in #72 we need to revert the changes in the train cfgs. The reason it was introduced: there were situations where the train cfg was used with pre-trained weights, which required the cfg to be changed. This situation can not happen anymore, hence it is changed back.

Revert changes to original vit cfgs

---

CHANGELOG.md
docs/source/models/rtdetr.md
src/lightly_train/_models/rtdetr/rtdetr.py
src/lightly_train/model_wrappers.py

- adds the custom wrapper for RT-DETR to a new module `lightly_train.model_wrappers`
- was tested locally. unit tests make no sense since RT-DETR is not pip-installable

Add RT-DETR ModelWrapper to `model_wrappers`

---

tests/_methods/distillation/test_distillation.py
tests/_methods/distillationv2/test_distillationv2.py

Added tests to verify that the teacher model is not saved in distillation methods.
The tests pass.

Add test to verify that the teacher is not saved.

---

src/lightly_train/_commands/train.py
src/lightly_train/_commands/train_helpers.py
src/lightly_train/_methods/densecl/densecl.py
src/lightly_train/_methods/dino/dino.py
src/lightly_train/_methods/dinov2/dinov2.py
src/lightly_train/_methods/distillation/distillation.py
src/lightly_train/_methods/method_args.py
tests/_commands/test_train.py
tests/_commands/test_train_helpers.py
tests/_methods/densecl/__init__.py
tests/_methods/densecl/test_densecl.py
tests/_methods/dino/__init__.py
tests/_methods/dino/test_dino.py
tests/_methods/dinov2/test_dinov2.py
tests/_methods/distillation/test_distillation.py
tests/_methods/simclr/__init__.py
tests/_methods/simclr/test_simclr.py

Change the interface of `train_helpers.get_method_args` and `MethodArgs.resolve_auto` to use ModelWrapper as input and adjust the unit tests accordingly.
Passed unit test.

Use ModelWrapper in `get_method_args`

---

src/lightly_train/_models/torchvision/shufflenet.py
tests/_models/dinov2_vit/test_dinov2_vit.py
tests/_models/rfdetr/test_rfdetr.py
tests/_models/super_gradients/test_segmentation_module.py
tests/_models/timm/test_timm.py
tests/_models/torchvision/test_convnext.py
tests/_models/torchvision/test_resnet.py
tests/_models/torchvision/test_shufflenet.py
tests/_models/ultralytics/test_ultralytics.py

* Add test that model wrappers register all modules correctly
I noticed that I introduced a bug for shufflenet in #128 which doesn't register the module correctly. This PR fixes the bug and adds tests for all other wrappers as well. I used the "meta" device because it is always available. It raises an error if any of the parameters is still on a "cpu" or "cuda" device. 
* Add unit tests

Test ModelWrapper move to device

---

src/lightly_train/_methods/dinov2/dinov2.py
src/lightly_train/_methods/method.py
tests/_methods/dinov2/test_dinov2.py

* Add log dict to training step result
* Remove `training_step` implementation from DINOv2
This PR structures the loss logs for DINOv2 and puts them into a single `train_loss` group. This avoids that we create a mess in the logging tools of our users.
* Manually
TensorBoard:
WandB

Add log dict to TrainingStepResult

---

CHANGELOG.md
src/lightly_train/_methods/distillation/distillation.py
src/lightly_train/_methods/distillationv2/distillationv2.py
src/lightly_train/_models/dinov2_vit/dinov2_vit_package.py
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/configs/__init__.py
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/configs/train/_vit_test14.yaml
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/models/vision_transformer.py
tests/_methods/dinov2/test_dinov2.py
tests/_methods/distillation/test_distillation.py
tests/_methods/distillationv2/test_distillationv2.py
tests/helpers.py

Support loading DINOv2 teacher weights from a pretrained checkpoint by allowing such input
```
lightly_train.train(
...,
method="distillation",
method_args={
"teacher": "dinov2_vit/vitb14",
"teacher_weights": "out/dinov2/exported_models/exported_last.pt", # pretrained `dinov2_vit/vitb14` weights 
}
)
```
Also added unit tests for this. More specifically, to enable the test, we
- renamed `vit_tiny__testing` to `_vit_test` and added it to the available model list so that it can be loaded via `lightly_train.train(model="dinov2_vit/_vit_test")
- moved `dummy_vit_model` to `helpers` so that it can be used across all the tests
By running the unit tests.

Allow DINOv2 weights loading for Distillation

---

src/lightly_train/_methods/dinov2/dinov2.py

The DINOv2 local loss was not correctly initialized which caused an error if the number of local crops was set to zero.
Dummy runs.

Fix DINOv2 local loss initialization

---

CHANGELOG.md
README.md
docs/source/index.md
docs/source/models/rtdetr.md

- We are actually only supporting the RT-DETRv2 package, however this can also be used with the RT-DETRv1 configs.
- This PR streamlines the naming as follows: The package is always called RT-DETR, the model is always called RT-DETRv2
- I additionally included all the v2 configs that had previously not been in the documentation
- I excluded all the `hgnetv2` models, e.g. https://github.com/lyuwenyu/RT-DETR/blob/main/rtdetrv2_pytorch/configs/rtdetrv2/rtdetrv2_hgnetv2_h_6x_coco.yml, since they don't run with LightlyTrain.
@yutong-xiang-97 update: makes explicit that users can train v1 models with v2 package.
- manually ran all the supported models once locally
- I would not implement unit tests for all the models, this would take forever

Update Documentation of RT-DETR Models

---

src/lightly_train/_commands/train_task.py
src/lightly_train/_commands/train_task_helpers.py
src/lightly_train/_loggers/task_logger_args.py

Use Lightning's MLflow logger for logging.
Note that:
1. The resolution of the accelerator and strategy does not work for now
2. We didn't add the corresponding unit test because the settings will be too cumbersome.
run `test_train_task` with a script using the MLflow service.

VFMF Add MLflow Logger

---

src/lightly_train/_commands/export_task.py
tests/_methods/dinov2/test_dinov2.py

Fix unit test:
- remove `torch.use_deterministic_algorithms(True)` in `export_task` to fix failures
- add `optim.step()` in `test_dinov2::test_layerwise_decay_optimizer` to fix the warning: 
```
UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. 
```
Successful checks.

Fix Unit Tests

---

CHANGELOG.md
src/lightly_train/_methods/distillationv2/distillationv2.py
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/layers/patch_embed.py
src/lightly_train/_models/dinov2_vit/dinov2_vit_src/models/vision_transformer.py
src/lightly_train/_plot.py

Update the DINOv2 ViT to support square images with resolution that is not a multiple of the patch size.
Update the plotting of augmentations for odd size image resolutions
Dummy runs with various resolutions (square only).

Thomas trn 625 allow arbitrary input size

---

src/lightly_train/_commands/train_task.py
src/lightly_train/_commands/train_task_helpers.py
src/lightly_train/_task_models/dinov2_eomt_semantic_segmentation/train_model.py

The mask annealing steps are automatically inferred such that it works for datasets other than ADE20K.
Verified that the inferred steps are close to the original values for ADE20K.

Thomas trn 1368 fix mask annealing steps

---

CHANGELOG.md
src/lightly_train/_callbacks/checkpoint.py

- solves https://github.com/lightly-ai/lightly-train/issues/174
- exposes the filename for the checkpoints and lets users customize it
- tested with a local training run
```python
import lightly_train
if __name__ == "__main__":
lightly_train.train(
out="out/my_experiment",            # Output directory
data="my_data_dir",                 # Directory with images
model="torchvision/resnet18",       # Model to train
epochs=10,                          # Number of epochs to train
batch_size=32,                      # Batch size
accelerator="cpu",
overwrite=True,
callbacks={
"model_checkpoint": {
"filename": "some_custom_name_{epoch}_{train_loss:.2f}",
},
}
)
```
and the resulting checkpoint was at `out/my_experiment/checkpoints/some_custom_name_epoch=1_train_loss=3.12.ckpt`.

Allow custom filenames for checkpoints

---

src/lightly_train/_data/_serialize/memory_mapped_sequence.py
tests/_data/_serialize/test_memory_mapped_sequence.py

* Lazily initialize mmap tables on every process individually
This avoids potential issues where table references could be shared across processes.
* Unit tests
* Manually on multi-GPU

Lazy init mmap table

---

src/lightly_train/_commands/train_task.py
src/lightly_train/_commands/train_task_helpers.py
src/lightly_train/_task_models/dinov2_eomt_semantic_segmentation/train_model.py
src/lightly_train/_task_models/train_model.py

The number joint blocks is automatically inferred in EoMT to accommodate other models than the ViT-L
-

Infer num_joint_blocks from model name

---

CHANGELOG.md
src/lightly_train/_commands/train_task_helpers.py
src/lightly_train/_data/mask_semantic_segmentation_dataset.py
tests/_data/test_mask_semantic_segmentation_dataset.py

Allow mapping multiple classes to a single class for training when using `train_semantic_segmentation` command. More specifically, we now allow the following input format for `classes` in the `data` argument:
```python
classes={
255: {"name": "background", "values": [0, 1, 2]},
3: {"name": "class 3", "values": [3]},
}
```
Use the `"name"` to specify the name of the new label, and `"values"` to specify all the class labels to be mapped. 
Note that one can still pass a single string as the label name in the `classes` dict, i.e. the following works:
```python
classes: dict[int, ClassInfo] = {
255: {"name": "background", "values": [0, 1, 2]},
3: "class 3", 
}
```
Internally, all the inputs will be mapped as such:
```python
classes: dict[int, ClassInfo] = {
255: {"name": "background", …
```

Add semantic segmentation class mapping support

---

src/lightly_train/_commands/export_task.py
tests/_commands/test_export_task.py

This PR makes it so that when we export an ONNX model and the iamge size is not divisible by the patch size, we raise a ValueError that explains what is going on. Previously the user would get a confusing RuntimeError.
Case is covered by two new tests.
We get an exception anyways if the image size is not correct, this just gives a gentler error message.
No documentation yet

Raise ValueError during ONNX export if image size not divisible by patch size

---

CHANGELOG.md
docs/prebuild.py
src/lightly_train/_commands/common_helpers.py
src/lightly_train/_commands/embed.py
src/lightly_train/_commands/train.py
tests/_commands/test_common_helpers.py

* Speed up logging of datasets with many files
* Make sure we always prune excessively long lists before logging
Adresses #264 partially
* Unit tests
* Manually

Speed up logging of datasets with many files

---

src/lightly_train/_task_models/dinov2_linear_semantic_segmentation/task_model.py

Fix the grid size in linear segmentation for resolutions that are not multiple of 14.
Manual test.

Fix grid size in linear segmentation

---

README.md

- banner is outdated
- new banner:

Update README conference banner

---

CHANGELOG.md
src/lightly_train/_methods/dinov2/dinov2.py

- the ceiling operation leads to a warning when using the "auto" epoch setting
- changing to `floor` from `ceil` should fix it
- not

Use floor operation in determining DINOv2 epochs
